<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InventoryManagement.Core\InventoryManagement.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands\EmployeeCommands\" />
    <Folder Include="Commands\ReceiptCommands\" />
    <Folder Include="Commands\ProductCommands\" />
    <Folder Include="DTOs\CommandDTOs\EmployeeCommandDTOs\" />
    <Folder Include="DTOs\CommandDTOs\InventoryCommandDTOs\" />
    <Folder Include="DTOs\CommandDTOs\ReceiptItemCommandDTOs\" />
    <Folder Include="DTOs\CommandDTOs\ReceiptCommandDTOs\" />
    <Folder Include="DTOs\CommandDTOs\ProductCommandDTOs\" />
    <Folder Include="DTOs\QueryDTOs\DepartmentQueryDTOs\" />
    <Folder Include="Queries\DepartmentQueries\" />
  </ItemGroup>

</Project>
